title: Configuration
data:
  error_404_entry: 059d4d8d-fc60-49f8-8823-7da10549e84e
  copyright_name: 'RV Waarloos vzw'
  copyright_since: 2020
  privacy_statement_type: none
  cookie_notice_type: none
